# Generated by Django 6.0.3 on 2026-04-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=50, verbose_name='first_Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['id'],
            },
        ),
    ]
